default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  encoding: unicode

development:
  <<: *default
  database: music_service_api_dev

test:
  <<: *default
  database: music_service_api_test
