default: &default
  :elasticsearch:
    :host: '<%= ENV['SEARCHBOX_URL']%>'


development:
  <<: *default

  :elasticsearch:
    :host: 'http://localhost:9200'

staging:
  <<: *default

production:
  <<: *default
