default: &default
  :elasticsearch:
    :host: '<%= ENV['SEARCHBOX_URL']%>'


development:
  :elasticsearch:
    :host: 'http://localhost:9200'

test:
  :elasticsearch:
    :host: 'http://localhost:9250'


production:
  <<: *default
