default: &default
  :elasticsearch:
    :host: '<%= ENV['SEARCHBOX_URL']%>'

  :sidekiq_web:
    :user: '<%= ENV['SIDEKIQ_USER']%>'
    :passwd: '<%= ENV['SIDEKIQ_PASSWORD']%>'


development:
  :elasticsearch:
    :host: 'http://localhost:9200'

test:
  :elasticsearch:
    :host: 'http://localhost:9200'

production:
  <<: *default
